name: Action on Pull Request to generate Kong Config from Spec and Validate it

on:
  pull_request:
    branches:
      - master

jobs:
  deploy_to_kong:
    runs-on: self-hosted
    name: Generate Kong config from Spec and Validate config
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Change directory to openapi
        run: cd openapi
      # - name: Setup deck
      #   uses: kong/setup-deck@v1
      #   with:
      #     deck-version: '1.46.0'
      #     wrapper: false
      - name: Check deck version
        run: deck version
      - name: Convert OpenAPI to Kong
        run: 
          deck file openapi2kong --spec export.yaml --output-file kong.yaml
